name: Snaplet
options:
  createIntermediateGroups: true
targets:
  SnapletHost:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/SnapletCore
      - path: Apps/HostMac
        excludes:
          - Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arnavps.snaplet.host
        INFOPLIST_FILE: Apps/HostMac/Info.plist
        SWIFT_VERSION: 6.0
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_STRICT_CONCURRENCY: complete
  SnapletViewer:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources/SnapletCore
      - path: Apps/iOSViewer
        excludes:
          - Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arnavps.snaplet.viewer
        INFOPLIST_FILE: Apps/iOSViewer/Info.plist
        SWIFT_VERSION: 6.0
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: 6NSBP8HC67
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_STRICT_CONCURRENCY: complete
